version: '3.8'

# Production environment - roberthauta.com

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: resume-mongodb-prod
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: resume_db
    volumes:
      - mongodb_prod_data:/data/db
      - ./mongodb-backup:/backup
    networks:
      - resume-network-prod
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-roberthauta}/resume-backend:latest
    container_name: resume-backend-prod
    restart: unless-stopped
    env_file:
      - .env.backend.prod
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - resume-network-prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # React Frontend
  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-roberthauta}/resume-frontend:latest
    container_name: resume-frontend-prod
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - resume-network-prod
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx Proxy
  nginx-proxy:
    image: nginx:alpine
    container_name: resume-nginx-proxy-prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - resume-network-prod
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  resume-network-prod:
    driver: bridge

volumes:
  mongodb_prod_data:
    driver: local