version: '3.8'

# Development environment - runs on dev.roberthauta.com with HTTPS

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: resume-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: resume_db
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - resume-network-dev

  # FastAPI Backend
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: resume-backend-dev
    restart: unless-stopped
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=resume_db
      - SECRET_KEY=dev-secret-key-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - API_V1_PREFIX=/api/v1
      - PROJECT_NAME=Resume API - Dev
      - BACKEND_CORS_ORIGINS=["https://dev.roberthauta.com", "http://dev.roberthauta.com"]
    depends_on:
      - mongodb
    volumes:
      - ../backend/app:/app/app
    networks:
      - resume-network-dev

  # React Frontend
  frontend:
    image: node:20-alpine
    container_name: resume-frontend-dev
    restart: unless-stopped
    working_dir: /app
    environment:
      - VITE_API_URL=https://dev.roberthauta.com/api/v1
    volumes:
      - ../frontend:/app
      - /app/node_modules
    command: sh -c "yarn install && yarn dev --host 0.0.0.0 --port 80"
    depends_on:
      - backend
    networks:
      - resume-network-dev

  # Nginx Proxy with HTTPS
  nginx-proxy:
    image: nginx:alpine
    container_name: resume-nginx-dev
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - resume-network-dev

networks:
  resume-network-dev:
    driver: bridge

volumes:
  mongodb_dev_data:
    driver: local