name: CI - Lint and Test

on:
  pull_request:
    branches: [main, qa]
  push:
    branches: [main, qa]

jobs:
  backend-lint:
    name: Backend Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install ruff black
          pip install -r requirements.txt

      - name: Run Ruff
        working-directory: ./backend
        run: ruff check app/

      - name: Run Black
        working-directory: ./backend
        run: black --check app/

  frontend-lint:
    name: Frontend Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./frontend
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        working-directory: ./frontend
        run: yarn lint

      - name: Type check
        working-directory: ./frontend
        run: yarn run tsc --noEmit

  frontend-build:
    name: Frontend Build Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./frontend
        run: yarn install --frozen-lockfile

      - name: Build
        working-directory: ./frontend
        run: yarn build